package Patient;

import java.sql.*;
import javax.swing.JOptionPane;

public class UpdatePateint extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UpdatePateint.class.getName());

    /**
     * Creates new form UpdatePateint
     */
    public UpdatePateint() {
        initComponents();
        this.setLocationRelativeTo(null);
        jButton1.setFont(null);
        this.setTitle("🔧Update");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        txt_age = new javax.swing.JTextField();
        txt_num = new javax.swing.JTextField();
        txt_gender = new javax.swing.JTextField();
        txt_blood = new javax.swing.JTextField();
        txt_add = new javax.swing.JTextField();
        txt_Lname = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        txt_Fname = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Patient ID :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 90, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Last Name :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 130, 88, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Contact No :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 100, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Age :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 190, 88, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Gender :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 88, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Address :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 88, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Blood Group :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 260, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Any Major Disease suuffered Earlier :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 340, 280, -1));

        txt_id.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, 226, -1));

        txt_age.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_age.setText(" ");
        txt_age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ageActionPerformed(evt);
            }
        });
        getContentPane().add(txt_age, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 190, 226, -1));

        txt_num.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_num.setText(" ");
        getContentPane().add(txt_num, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 226, -1));

        txt_gender.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_gender.setText(" ");
        getContentPane().add(txt_gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, 226, -1));

        txt_blood.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_blood.setText(" ");
        getContentPane().add(txt_blood, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 260, 226, -1));

        txt_add.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txt_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, 226, -1));

        txt_Lname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_Lname.setText(" ");
        getContentPane().add(txt_Lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 123, 226, 30));

        jTextField8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField8.setText(" ");
        getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 380, 350, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("🔍Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 60, 100, 30));

        jButton2.setBackground(new java.awt.Color(255, 153, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("💾Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 550, 200, 90));

        jButton3.setBackground(new java.awt.Color(0, 255, 204));
        jButton3.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("🚪Close");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 550, 210, 90));

        txt_Fname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_Fname.setText(" ");
        txt_Fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_FnameActionPerformed(evt);
            }
        });
        getContentPane().add(txt_Fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 226, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("First Name :");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 88, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/AddPatin.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_ageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ageActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String patientID = txt_id.getText();

        if (!patientID.matches("\\d+")) {

            JOptionPane.showMessageDialog(null, "Please Enter The number");
            return;
        }

        try {
            Connection con = DB.getConnection();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM Patients WHERE PatientID = " + patientID);
            if (rs.next()) {

                txt_Fname.setText(rs.getString("FirstName"));
                txt_Lname.setText(rs.getString("LastName"));
                txt_num.setText(rs.getString("Phone"));
                txt_age.setText(rs.getString("Age"));
                txt_gender.setText(rs.getString("Gender"));
                txt_blood.setText(rs.getString("BloodGroup"));
                txt_add.setText(rs.getString("Address"));
                jTextField8.setText(rs.getString("AnyMajor"));
                txt_id.setEditable(false);
            } else {
                JOptionPane.showMessageDialog(null, "PatientID does not exist");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Connection Error ❌");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        String patient = txt_id.getText();
        String Firstname = txt_Fname.getText();
        String Lastname = txt_Lname.getText();
        String Age = txt_age.getText();
        String blood = txt_blood.getText();
        String add = txt_add.getText();
        String gender = txt_gender.getText();
        String Phone = txt_num.getText();
        String anymajor = jTextField8.getText();
        int patientID = Integer.parseInt(patient.trim());
        Connection con = null;
        PreparedStatement ps = null;
        try {
            con = DB.getConnection();
            String sql = "update Patients SET Phone=?,Age=?,FirstName=?,LastName=?,Gender=?,BloodGroup=?,Address=?,AnyMajor=? WHERE PatientID=?";
            ps = con.prepareStatement(sql);

            if (!Age.matches("\\d+")) {

                JOptionPane.showMessageDialog(null, "Please Enter The number in Age");
                return;
            }

            ps.setString(1, Phone);
            ps.setString(2, Age);
            ps.setString(3, Firstname);
            ps.setString(4, Lastname);
            ps.setString(5, gender);
            ps.setString(6, blood);
            ps.setString(7, add);
            ps.setString(8, anymajor);
            ps.setInt(9, patientID);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Successfully Updated ✅");
            new UpdatePateint().setVisible(true);
            setVisible(false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "enter data in correct fromate!");
        } finally {
            try {
                if (ps != null) {
                    ps.close();
                }
                if (con != null) {
                    con.close();
                }
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        new Patient.HomePatient().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txt_FnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_FnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_FnameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new UpdatePateint().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField txt_Fname;
    private javax.swing.JTextField txt_Lname;
    private javax.swing.JTextField txt_add;
    private javax.swing.JTextField txt_age;
    private javax.swing.JTextField txt_blood;
    private javax.swing.JTextField txt_gender;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_num;
    // End of variables declaration//GEN-END:variables
}
