package Doctors;

import java.sql.*;
import javax.swing.JOptionPane;

public class UpdateDoctor extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UpdateDoctor.class.getName());

    public UpdateDoctor() {
        initComponents();
        this.setLocationRelativeTo(null);
        jButton1.setFont(null);
        this.setTitle("🔧Update");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        txt_age = new javax.swing.JTextField();
        txt_num = new javax.swing.JTextField();
        txt_gender = new javax.swing.JTextField();
        txt_add = new javax.swing.JTextField();
        txt_Lname = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        txt_Fname = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_Spec = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 204));
        jLabel1.setText("Patient ID :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 120, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Last Name :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(568, 150, 130, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Contact No :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 120, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Age :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 230, 88, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("Gender :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 100, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("Address :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(608, 320, 90, -1));

        txt_id.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, 226, -1));

        txt_age.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_age.setText(" ");
        txt_age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ageActionPerformed(evt);
            }
        });
        getContentPane().add(txt_age, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 230, 226, -1));

        txt_num.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_num.setText(" ");
        getContentPane().add(txt_num, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 226, -1));

        txt_gender.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_gender.setText(" ");
        getContentPane().add(txt_gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 226, -1));

        txt_add.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txt_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 320, 226, -1));

        txt_Lname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_Lname.setText(" ");
        getContentPane().add(txt_Lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 150, 226, -1));

        jButton1.setBackground(new java.awt.Color(255, 153, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("🔍Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 60, 100, 30));

        jButton2.setBackground(new java.awt.Color(0, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 0, 0));
        jButton2.setText("🔧Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 540, 220, 90));

        jButton3.setBackground(new java.awt.Color(255, 0, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(153, 255, 255));
        jButton3.setText("🚪Close");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 540, 210, 90));

        txt_Fname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_Fname.setText(" ");
        getContentPane().add(txt_Fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 226, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("First Name :");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 120, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("Specialist : ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 410, 130, -1));

        txt_Spec.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txt_Spec, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 410, 226, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Doctor3.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, -30, 1740, 1160));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_ageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ageActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String DoctorID = txt_id.getText();

        if (!DoctorID.matches("\\d+")) {

            JOptionPane.showMessageDialog(null, "Please Enter The number");
            return;
        }

        try {
            Connection con = DB.getConnection();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM Doctors WHERE DoctorID = " + DoctorID);
            if (rs.next()) {

                txt_Fname.setText(rs.getString("FirstName"));
                txt_Lname.setText(rs.getString("LastName"));
                txt_num.setText(rs.getString("Phone"));
                txt_age.setText(rs.getString("Age"));
                txt_gender.setText(rs.getString("Gender"));
                txt_add.setText(rs.getString("Address"));
                txt_id.setEditable(false);
                txt_Spec.setText(rs.getNString("Specialest"));

            } else {
                JOptionPane.showMessageDialog(null, "DoctorsID does not exist");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Failed Updated❌ " + e.getMessage());

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        String Doctors = txt_id.getText();
        String Firstname = txt_Fname.getText();
        String Lastname = txt_Lname.getText();
        String Age = txt_age.getText();
        String add = txt_add.getText();
        String gender = txt_gender.getText();
        String Phone = txt_num.getText();
        String Spec = txt_Spec.getText();

        Connection con = null;
        PreparedStatement ps = null;

        if (!Doctors.matches("\\d+")) {
            JOptionPane.showMessageDialog(null, "❌ Please enter numbers only!");
            return;
        }

        int DoctorsId = Integer.parseInt(Doctors.trim());

        try {
            con = DB.getConnection();
            String sql = "UPDATE Doctors SET Phone=?, Age=?, FirstName=?, LastName=?, Gender=?, Address=?, Specialest=? WHERE DoctorID=?";
            ps = con.prepareStatement(sql);

            ps.setString(1, Phone);
            ps.setString(2, Age);
            ps.setString(3, Firstname);
            ps.setString(4, Lastname);
            ps.setString(5, gender);
            ps.setString(6, add);
            ps.setString(7, Spec);
            ps.setInt(8, DoctorsId);

            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Successfully Updated");

        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(null, "Enter data in correct format!");
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        new HomeDoctor().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new UpdateDoctor().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txt_Fname;
    private javax.swing.JTextField txt_Lname;
    private javax.swing.JTextField txt_Spec;
    private javax.swing.JTextField txt_add;
    private javax.swing.JTextField txt_age;
    private javax.swing.JTextField txt_gender;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_num;
    // End of variables declaration//GEN-END:variables
}
